### ISSUE TITLE
"set fit quiet" causes older gnuplot versions to fail to display graph

### ISSUE THREAD

**Issue by velotraveler** [hans-mayer/ntpgraph#2]
I was using ntpgraph on some RHEL 6.x hosts which default to an older version of gnuplot, and the commands "set fit quiet" were causing gnuplot to error off without displaying the graph.  Apparently "set fit quiet" was not introduced until gnuplot 4.6 and many distros still use older versions.

I replaced "set fit quiet" with "set fit logfile "/dev/null" " on the affected machines and was able to generate the graphs.

**Comment by hans-mayer** [comment]
ok, i see the point. in "ntp_shps" i made a change depending on gnuplot version. pull the latest commit from my repo and let me know if OK. if so i will implement this in "ntp_shdiff" too. 

// hans

**Comment by velotraveler** [comment]
The new ntp_shps works as expected with gnuplot 4.2, on a system that printed the error message with the previous commit a188130f965b65d790ebfca45beaeb1a26d197d4 .  Looks good, thank you!

**Comment by hans-mayer** [comment]
"ntp_shdiff" is adapted too.
